#!/bin/bash
echo "Rotating item 1 $(date +\"%T\") (href, icon) |iconName=dialog-ok href=http://www.google.com"
echo "Rotating item 2 $(date +\"%T\") (bash, imageURL) | bash=ls imageURL=http://doc.qt.io/qt-5/images/declarative-qtlogo.png"
echo "Rotating item 3 $(date +\"%T\") (bash, icon, font, href) | iconName=dialog-cancel bash=ls font=serif href=http://www.google.com"
echo "Rotating item 4 $(date +\"%T\") (font, size) | size=14 font=serif"
echo "---"
echo "Dropdown item 1 $(date +\"%T\") (href, icon, image) |iconName=dialog-ok href=http://www.google.com image=$(wget -O - http://doc.qt.io/qt-5/images/declarative-qtlogo.png | base64 -w0)"
echo "Dropdown item 2 $(date +\"%T\") (bash, imageURL) | bash=ls imageURL=http://doc.qt.io/qt-5/images/declarative-qtlogo.png"
echo "Dropdown item 3 $(date +\"%T\") (bash, icon, font, href) | iconName=dialog-cancel bash=ls font=serif  href=http://www.google.com"
echo "Dropdown item 4 $(date +\"%T\") (font, size) | size=14 font=serif"
echo "NoDropdown item 4 $(date +\"%T\") (dropdown=false) | dropdown=false"
echo "Menu"
echo "-- submenu item 1 $(date +\"%T\") (href, icon)|iconName=dialog-ok href=http://www.google.com"
echo "-- submenu item 2 $(date +\"%T\") (href) | href=http://www.google.com"
echo "-- submenu item 3 $(date +\"%T\") (bash, icon, font) | iconName=dialog-cancel bash=ls font=serif"
echo "-- submenu item 4 $(date +\"%T\") (font, size) | size=14 font=serif"
echo "Menu 2"
echo "-- submenu2 item 1 $(date +\"%T\") (href, icon)|iconName=dialog-ok href=http://www.google.com"
echo "-- submenu2 item 2 $(date +\"%T\") (href) | href=http://www.google.com"
echo "-- submenu2 item 3 $(date +\"%T\") (bash, icon, font) | iconName=dialog-cancel bash=ls font=serif"
echo "-- submenu2 item 4 $(date +\"%T\") (font, size) | size=14 font=serif"